repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.4.0
  hooks:
  - id: check-yaml
  - id: check-json
    exclude: data/
  - id: check-added-large-files
    args: ['--maxkb=25000']
  - id: end-of-file-fixer
    exclude: data/
  - id: trailing-whitespace
    exclude: data/
  - id: check-case-conflict
  - id: mixed-line-ending
    exclude: data/

- repo: https://github.com/psf/black
  rev: 20.8b1
  hooks:
  - id: black

- repo: https://github.com/timothycrosley/isort
  rev: 5.7.0
  hooks:
  - id: isort

- repo: https://gitlab.com/pycqa/flake8
  rev: 3.8.4
  hooks:
  - id: flake8
    additional_dependencies: [flake8-bugbear]

- repo: https://github.com/nbQA-dev/nbQA
  rev: 0.5.7
  hooks:
  - id: nbqa-black
    additional_dependencies: [black==20.8b1]
  - id: nbqa-isort
    additional_dependencies: [isort==5.7.0]
  #- id: nbqa-flake8
  #  additional_dependencies: [flake8==3.8.4]
  #  exclude: advanced-machine-learning-and-signal-processing/Examples/|spark-fundamentals-I/
